services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: todouser  
      POSTGRES_PASSWORD: todopass
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://todouser:todopass@db:5432/todoapp
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Hot reload for development
    depends_on:
      - db